repos:
-   repo:     https://github.com/pre-commit/pre-commit-hooks
    rev:      v2.3.0
    hooks:
    -   id:   check-toml
    -   id:   check-yaml
    -   id:   debug-statements
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.761'
    hooks:
    -   id: mypy
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.2
    hooks:
    -   id: pydocstyle
